### PR TITLE
feature: support jpg- and png-images in pdf

### PR DESCRIPTION
**Pull request by vanvuongngo**
- [x] Supports logo/ images in jpg or png format

### CODE REVIEW

**Comment by schoero** [comment]
Thank you for your contribution, I really appreciate that!

However, I don't see much benefits in this wrapper method over calling `this.image()` directly.
I would try to avoid such wrappers, since someone who wants to create an invoice, already has to read the original PDFKit documentation for other methods.
Wrapper functions only make the codebase more complex and harder to maintain. In addition to that, the [original documentation](http://pdfkit.org/docs/images.html) is much more detailed.

If the intent of this pull request is to make it more clear that it is also possible to add raster images, I would suggest to just mention it in [how-to-create-a-complete-bill.md](https://github.com/schoero/SwissQRBill/blob/0c4ca0b09d4e4a6bf18df985bd075a02a60792cb/doc/how-to-create-a-complete-bill.md?plain=1#L67)

**Comment by schoero** [comment]
Thank you for your contribution, I really appreciate that!

However, I don't see much benefits in this wrapper method over calling `this.image()` directly.
I would try to avoid such wrappers, since someone who wants to create an invoice, already has to read the original PDFKit documentation for other methods.
Wrapper functions only make the codebase more complex and harder to maintain. In addition to that, the [original documentation](http://pdfkit.org/docs/images.html) is much more detailed.

If the intent of this pull request is to make it more clear that it is also possible to add raster images, I would suggest to just mention it in [how-to-create-a-complete-bill.md](https://github.com/schoero/SwissQRBill/blob/0c4ca0b09d4e4a6bf18df985bd075a02a60792cb/doc/how-to-create-a-complete-bill.md?plain=1#L67)

**Comment by vanvuongngo** [comment]
Hi @schoero,
yes, my intent was to make it clear that it is also possible to add raster images. If it is already possible then please mention this feature in the how-to-create-a-complete-bill.md. It took me a while to figure out how to convert raster images to svg and without a good result.

**Comment by schoero** [comment]
Thank you for your feedback @vanvuongngo 

I try to make it more obvious 👍

**Pull request closed without merging**
